//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities1 : DbContext
    {
        public DbCvEntities1()
            : base("name=DbCvEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_About> Table_About { get; set; }
        public virtual DbSet<Table_Certificates> Table_Certificates { get; set; }
        public virtual DbSet<Table_Contact> Table_Contact { get; set; }
        public virtual DbSet<Table_Education> Table_Education { get; set; }
        public virtual DbSet<Table_Experience> Table_Experience { get; set; }
        public virtual DbSet<Table_Interests> Table_Interests { get; set; }
        public virtual DbSet<Table_Login> Table_Login { get; set; }
        public virtual DbSet<Table_Skills> Table_Skills { get; set; }
        public virtual DbSet<Table_SocialMedia> Table_SocialMedia { get; set; }
        public virtual DbSet<Table_ProgrammingLanguages> Table_ProgrammingLanguages { get; set; }
    }
}
